#include "oom.h"
#include "cfg.h"
#include "log.h"
#include "notify.h"

/* ----------------------------------------------------------------- detect -- */

static int is_executable(const char *path) {
    /* Use open() + fstat() instead of access() to avoid TOCTOU race */
    int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return 0;
    struct stat st;
    int ok = (fstat(fd, &st) == 0 &&
              S_ISREG(st.st_mode) &&
              (st.st_mode & (S_IXUSR | S_IXGRP | S_IXOTH)));
    close(fd);
    return ok;
}

static int has_systemd_oomd(void) {
    return is_executable(SYSTEMD_OOMD_BIN);
}

static int has_earlyoom(void) {
    return is_executable(EARLYOOM_BIN);
}

typedef enum {
    BACKEND_NONE = 0,
    BACKEND_OOMD,
    BACKEND_EARLYOOM,
} Backend;

static Backend resolve_backend(void) {
    if (strcasecmp(g_cfg.oom_backend, "none") == 0)       return BACKEND_NONE;
    if (strcasecmp(g_cfg.oom_backend, "systemd-oomd") == 0) {
        if (!has_systemd_oomd()) {
            LOGE("systemd-oomd not found at %s", SYSTEMD_OOMD_BIN);
            return BACKEND_NONE;
        }
        return BACKEND_OOMD;
    }
    if (strcasecmp(g_cfg.oom_backend, "earlyoom") == 0) {
        if (!has_earlyoom()) {
            LOGE("earlyoom not found at %s — install it first", EARLYOOM_BIN);
            return BACKEND_NONE;
        }
        return BACKEND_EARLYOOM;
    }
    /* auto: prefer systemd-oomd, fall back to earlyoom */
    if (has_systemd_oomd()) return BACKEND_OOMD;
    if (has_earlyoom())     return BACKEND_EARLYOOM;
    LOGW("No OOM backend found. Install systemd-oomd or earlyoom.");
    return BACKEND_NONE;
}

/* -------------------------------------------------------- memory detection -- */

typedef struct {
    unsigned long long total_kb;
    unsigned long long swap_kb;
    int swap_present;
} MemInfo;

static int read_meminfo(MemInfo *m) {
    memset(m, 0, sizeof(*m));
    FILE *f = fopen("/proc/meminfo", "r");
    if (!f) { LOGE("Cannot open /proc/meminfo: %s", strerror(errno)); return -1; }
    char line[128];
    while (fgets(line, (int)sizeof(line), f)) {
        unsigned long long v;
        if (sscanf(line, "MemTotal: %llu kB", &v) == 1)
            m->total_kb = v;
        else if (sscanf(line, "SwapTotal: %llu kB", &v) == 1) {
            m->swap_kb      = v;
            m->swap_present = (v > 0);
        }
    }
    fclose(f);
    return m->total_kb > 0 ? 0 : -1;
}

/* ------------------------------------------------ systemd-oomd configurator -- */

static int ensure_dir(const char *path) {
    if (mkdir(path, 0755) == 0) return 0;
    if (errno == EEXIST) {
        /* Verify it really is a directory */
        struct stat st;
        if (stat(path, &st) == 0 && S_ISDIR(st.st_mode)) return 0;
        LOGE("%s exists but is not a directory", path);
        return -1;
    }
    LOGE("mkdir(%s): %s", path, strerror(errno));
    return -1;
}

static int configure_oomd(const MemInfo *mem) {
    printf("\n[oom-policy] Backend: systemd-oomd\n");
    printf("  Memory: %llu MB\n", mem->total_kb / 1024);
    if (mem->swap_present)
        printf("  Swap:   %llu MB\n", mem->swap_kb / 1024);
    else
        printf("  Swap:   none\n");

    if (g_dry_run) {
        printf("  [DRY-RUN] would write drop-in: %s\n", OOMD_DROPIN_FILE);
        printf("  [DRY-RUN] would enable and start: %s\n", OOMD_SERVICE);
        return 0;
    }

    if (ensure_dir(OOMD_DROPIN_DIR) != 0) return -1;

    /*
     * Write a drop-in that sets swap and memory-pressure thresholds.
     * Values are clamped to sensible ranges.
     */
    int mem_pct  = g_cfg.oom_mem_threshold;
    int swap_pct = g_cfg.oom_swap_threshold;

    int dropin_fd = open(OOMD_DROPIN_FILE,
                         O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0644);
    if (dropin_fd < 0) {
        LOGE("Cannot write %s: %s", OOMD_DROPIN_FILE, strerror(errno));
        return -1;
    }
    FILE *f = fdopen(dropin_fd, "w");
    if (!f) { close(dropin_fd); return -1; }

    fprintf(f,
        "# Generated by %s v%s\n"
        "# Edit %s to change thresholds\n"
        "[OOM]\n"
        "SwapUsedLimit=%d%%\n"
        "DefaultMemoryPressureLimit=%d%%\n"
        "DefaultMemoryPressureDurationSec=20s\n",
        PROG_NAME, NS_VERSION, DEFAULT_CONF_FILE,
        swap_pct, mem_pct);
    fflush(f);
    fsync(dropin_fd);
    fclose(f);
    LOGI("Wrote oomd drop-in: %s", OOMD_DROPIN_FILE);
    printf("  Wrote: %s\n", OOMD_DROPIN_FILE);
    printf("    SwapUsedLimit            = %d%%\n", swap_pct);
    printf("    DefaultMemoryPressureLimit = %d%%\n", mem_pct);

    /* Enable and start the service */
    {
        char *en_argv[]  = { SYSTEMCTL_BIN, "enable", "--now", OOMD_SERVICE, NULL };
        char *rel_argv[] = { SYSTEMCTL_BIN, "daemon-reload", NULL };
        proc_run_mut(SYSTEMCTL_BIN, rel_argv);
        if (proc_run_mut(SYSTEMCTL_BIN, en_argv) != 0) {
            LOGE("Failed to enable %s", OOMD_SERVICE);
            return -1;
        }
    }
    printf("  Enabled: %s\n", OOMD_SERVICE);
    LOGI("systemd-oomd configured and enabled");
    notify_send(SEV_INFO, "oom-policy",
                "systemd-oomd configured (mem=%d%% swap=%d%%)",
                mem_pct, swap_pct);
    return 0;
}

/* ------------------------------------------------- earlyoom configurator -- */

static int configure_earlyoom(const MemInfo *mem) {
    printf("\n[oom-policy] Backend: earlyoom\n");
    printf("  Memory: %llu MB\n", mem->total_kb / 1024);
    if (mem->swap_present)
        printf("  Swap:   %llu MB\n", mem->swap_kb / 1024);
    else
        printf("  Swap:   none\n");

    /* earlyoom uses -m (free memory %) and -s (free swap %) — these are
     * "free below X%" thresholds, so we invert our "used above X%" values. */
    int free_mem_pct  = 100 - g_cfg.oom_mem_threshold;
    int free_swap_pct = 100 - g_cfg.oom_swap_threshold;
    if (free_mem_pct  < 1) free_mem_pct  = 1;
    if (free_swap_pct < 1) free_swap_pct = 1;

    if (g_dry_run) {
        printf("  [DRY-RUN] would write: %s\n", EARLYOOM_CONF);
        printf("  [DRY-RUN] earlyoom args: -m %d -s %d -r 60 --avoid '(^)$'\n",
               free_mem_pct, free_swap_pct);
        printf("  [DRY-RUN] would enable: %s\n", EARLYOOM_SERVICE);
        return 0;
    }

    int fd = open(EARLYOOM_CONF,
                  O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0644);
    if (fd < 0) {
        LOGE("Cannot write %s: %s", EARLYOOM_CONF, strerror(errno));
        return -1;
    }
    FILE *f = fdopen(fd, "w");
    if (!f) { close(fd); return -1; }

    fprintf(f,
        "# Generated by %s v%s\n"
        "# Edit %s to change thresholds\n"
        "# earlyoom kills the process with highest memory score when:\n"
        "#   free memory  < %d%%  (used >= %d%%)\n"
        "#   free swap    < %d%%  (used >= %d%%)\n"
        "EARLYOOM_ARGS=\"-m %d -s %d -r 60 --prefer '(^systemd$|^init$)' --avoid '(^sshd$|^systemd$)'\"\n",
        PROG_NAME, NS_VERSION, DEFAULT_CONF_FILE,
        free_mem_pct,  g_cfg.oom_mem_threshold,
        free_swap_pct, g_cfg.oom_swap_threshold,
        free_mem_pct, free_swap_pct);
    fflush(f);
    fsync(fd);
    fclose(f);
    LOGI("Wrote earlyoom config: %s", EARLYOOM_CONF);
    printf("  Wrote: %s\n", EARLYOOM_CONF);
    printf("    free-mem threshold  = %d%% (kills when free < %d%%)\n",
           free_mem_pct, free_mem_pct);
    printf("    free-swap threshold = %d%% (kills when free < %d%%)\n",
           free_swap_pct, free_swap_pct);

    {
        char *en_argv[]  = { SYSTEMCTL_BIN, "enable", "--now", EARLYOOM_SERVICE, NULL };
        char *rel_argv[] = { SYSTEMCTL_BIN, "daemon-reload", NULL };
        proc_run_mut(SYSTEMCTL_BIN, rel_argv);
        if (proc_run_mut(SYSTEMCTL_BIN, en_argv) != 0) {
            LOGE("Failed to enable %s", EARLYOOM_SERVICE);
            return -1;
        }
    }
    printf("  Enabled: %s\n", EARLYOOM_SERVICE);
    LOGI("earlyoom configured and enabled");
    notify_send(SEV_INFO, "oom-policy",
                "earlyoom configured (free-mem<%d%% free-swap<%d%%)",
                free_mem_pct, free_swap_pct);
    return 0;
}

/* -------------------------------------------------------------- public API -- */

int oom_run(void) {
    /* Check privileges first — before touching any system paths */
    if (geteuid() != 0 && !g_dry_run) {
        fprintf(stderr, "oom-policy: root privileges required.\n");
        return -1;
    }

    MemInfo mem;
    if (read_meminfo(&mem) != 0) return -1;

    Backend b = resolve_backend();
    if (b == BACKEND_NONE) {
        printf("\n[oom-policy] No usable backend found or backend=none.\n");
        printf("  Install earlyoom:     pacman -S earlyoom\n");
        printf("  Or use systemd-oomd:  already in systemd (>= v247)\n");
        return 0;
    }

    if (b == BACKEND_OOMD)     return configure_oomd(&mem);
    if (b == BACKEND_EARLYOOM) return configure_earlyoom(&mem);
    return 0;
}
